### ISSUE TITLE
 ModuleNotFoundError - No module named '_cffi_backend'

### ISSUE THREAD

**Issue by ycng95** [aws-samples/decrypt-das-aws-rds#1]
Hi Sir, I follow all the prerequisite steps but still get this error in Cloudwatch, please advise. Thank you

[ERROR] ModuleNotFoundError: No module named '_cffi_backend'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 66, in lambda_handler
    if decrypt_decompress(payload_decoded, data_key_decrypt_result['Plaintext']) is None:
  File "/var/task/lambda_function.py", line 43, in decrypt_decompress
    decrypted = decrypt_payload(payload, key)
  File "/var/task/lambda_function.py", line 36, in decrypt_payload
    decrypted_plaintext, header = enc_client.decrypt(
  File "/opt/python/aws_encryption_sdk/__init__.py", line 196, in decrypt
    plaintext = decryptor.read()
  File "/opt/python/aws_encryption_sdk/streaming_client.py", line 260, in read
    self._prep_message()
  File "/opt/python/aws_encryption_sdk/streaming_client.py", line 792, in _prep_message
    self._header, self.header_auth = self._read_header()
  File "/opt/python/aws_encryption_sdk/streaming_client.py", line 830, in _read_header
    decryption_materials = self.config.materials_manager.decrypt_materials(request=decrypt_materials_request)
  File "/opt/python/aws_encryption_sdk/materials_managers/default.py", line 150, in decrypt_materials
    data_key = self.master_key_provider.decrypt_data_key_from_list(
  File "/opt/python/aws_encryption_sdk/key_providers/base.py", line 315, in decrypt_data_key_from_list
    data_key = self.decrypt_data_key(encrypted_data_key, algorithm, encryption_context)
  File "/opt/python/aws_encryption_sdk/key_providers/base.py", line 268, in decrypt_data_key
    data_key = master_key.decrypt_data_key(encrypted_data_key, algorithm, encryption_context)
  File "/opt/python/aws_encryption_sdk/key_providers/base.py", line 529, in decrypt_data_key
    decrypted_data_key = self._decrypt_data_key(
  File "/opt/python/aws_encryption_sdk/key_providers/raw.py", line 180, in _decrypt_data_key
    plaintext_data_key = self.config.wrapping_key.decrypt(
  File "/opt/python/aws_encryption_sdk/internal/crypto/wrapping_keys.py", line 105, in decrypt
    return decrypt(
  File "/opt/python/aws_encryption_sdk/internal/crypto/encryption.py", line 150, in decrypt
    decryptor = Decryptor(algorithm, key, associated_data, encrypted_data.iv, encrypted_data.tag)
  File "/opt/python/aws_encryption_sdk/internal/crypto/encryption.py", line 111, in __init__
    algorithm.encryption_algorithm(key), algorithm.encryption_mode(iv, tag), backend=default_backend()
  File "/opt/python/cryptography/hazmat/backends/__init__.py", line 14, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/opt/python/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/opt/python/cryptography/hazmat/backends/openssl/backend.py", line 113, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/opt/python/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib

**Comment by ycng95** [comment]
Solve by changing the Lambda function runtime to Python 3.7
